[package]
name = "monoxide"
version = "0.0.4"
authors = ["mehdi <mehdi.bcheikh@gmail.com>"]
edition = "2018"
documentation = "https://docs.rs/monoxide"
license = "Apache-2.0"
description = "A mongodb helper"

[dependencies]
serde = "1.0.126"
futures = "0.3.15"
bson = "1.2.2"
mongodb = "1.2.2"